# K6 resources act as a trigger for starting a test run.
#
# For this execution, we'll output test metrics to our free-tier Grafana Cloud
# account using credentials stored as Kubernetes Secret and a configurable
# remote write endpoint defined within a ConfigMap.
#
apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: k6-browser-test
spec:
  ## NOTE: There is a bug at this moment which does not allow more than 1 pod to run!
  parallelism: 1
  script:
    configMap:
      # Remember...we created the 'test-scripts' ConfigMap with the available scripts inside.
      # Recreate the ConfigMag if you modify scripts or want additional scripts.
      name: test-scripts
      # TODO - Want a different test script? Change it here.
      file: simple-browser.js
  runner:
    # TODO Change the image to your published image!
    image: javaducky/demo-k6-operator:latest
